; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    madhephaestus/ESP32Servo
    https://github.com/fanfanlatulipe26/FS_MX1508.git

[env:debug_stand]
build_src_filter =
    +<apps/debug_stand/>
    +<common/>

[env:FW_SW_debug_stand]
build_src_filter =
    +<apps/FW_SW_debug_stand/>
    +<common/>

[env:mechanic_debug_stand]
build_src_filter =
    +<apps/mechanic_debug_stand/>
    +<common/>